name: Keep Repository Active

on:
  schedule:
    - cron: '0 12 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keepalive-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Create empty keepalive commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore: keepalive commit to prevent actions suspension"
          git push
